## Problem 3 - Data analysis (4 points)

In this problem we will explore our temperature data by comparing spring temperatures between Helsinki Kumpula and Rovaniemi. To do this we'll use some conditions to extract subsets of our data and then analyse these subsets using basic pandas functions. Please perform the tasks below by writing your code into the code cells in each section.

### Tips for completing this problem

- Use **exactly** the same variable names as in the instructions because your answers will be automatically graded, and the tests that grade your answers rely on following the same formatting or variable naming as in the instructions.
- **Please do not**:

    - **Change the file names**. Do all of your editing in the provided `Exercise-5-problem-3.ipynb` file (this file).
    - **Copy/paste cells in this notebook**. We use an automated grading system that will fail if there are copies of code cells.
    - **Change the existing cell types**. You can add cells, but changing the cell types for existing cells (from code to markdown, for example) will also cause the automated grader to fail. 

### Scores for this problem

**Your score on this problem will be based on following criteria:**

- Calculating the median temperatures for Helsinki Kumpula and Rovaniemi for the summer of 2017
- Selecting temperatures for May and June 2017 in separate dataframes for each location
- Printing out some summary values for each month (May, June) and location (Kumpula, Rovaniemi)
- Including comments that explain what most lines in the code do
- Answering a couple questions at the end of the problem
- Uploading your notebook and data files to your GitHub repository for this week's exercise

## AI tool usage agreement

**Enter your name (and that of your partner) in the cell below** to confirm that you have followed the [course guidelines on the use of AI tools](https://geo-python-site.readthedocs.io/en/latest/course-info/ai-tools.html) and understand that misuse of AI tools is considered cheating.

YOUR ANSWER HERE

### Part 1 (0 points)

First, you need to load the data from Problem 2.

- Read in the csv files generated in Problem 2 to the variables `kumpula` and `rovaniemi`

In [ ]:
!pip install pandas # to install the library if it is not available

In [1]:
import pandas as pd

In [5]:
kumpula = pd.read_csv("data/Kumpula_temps_May_Aug_2017.csv", sep=",")
rovaniemi = pd.read_csv("data/Rovaniemi_temps_May_Aug_2017.csv", sep=",")

   Unnamed: 0   USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0        8770  29980  201705010000  37.0  NaN  NaN  2.777778
1        8771  29980  201705010100  37.0  NaN  NaN  2.777778
2        8772  29980  201705010200  37.0  NaN  NaN  2.777778
3        8773  29980  201705010300  37.0  NaN  NaN  2.777778
4        8774  29980  201705010400  39.0  NaN  NaN  3.888889

In [6]:
print(kumpula.head())
print("")
print(rovaniemi.head())

   Unnamed: 0   USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0        8770  29980  201705010000  37.0  NaN  NaN  2.777778
1        8771  29980  201705010100  37.0  NaN  NaN  2.777778
2        8772  29980  201705010200  37.0  NaN  NaN  2.777778
3        8773  29980  201705010300  37.0  NaN  NaN  2.777778
4        8774  29980  201705010400  39.0  NaN  NaN  3.888889

   Unnamed: 0   USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0           0  28450  201705010000  31.0  NaN  NaN -0.555556
1           1  28450  201705010020  30.0  NaN  NaN -1.111111
2           2  28450  201705010050  30.0  NaN  NaN -1.111111
3           3  28450  201705010100  31.0  NaN  NaN -0.555556
4           4  28450  201705010120  30.0  NaN  NaN -1.111111

### Part 2 (1 points)

Next you can find the *median temperatures* for the period the data covers.

- What was the median Celsius temperature during the observed period in:
    - Helsinki Kumpula? (store the answer in a variable `kumpula_median`)
    - Rovaniemi? (store the answer in a variable `rovaniemi_median`)

In [10]:
kumpula_median = kumpula["TEMP"].median()
rovaniemi_median = rovaniemi["TEMP"].median()

In [11]:
# Prints the median temperatures
print(f"Kumpula median: {kumpula_median}")
print(f"Rovaniemi median: {rovaniemi_median}")

Kumpula median: 58.0
Rovaniemi median: 52.0

### Part 3 (2 points)

The median temperatures above consider data from the entire summer (May-Aug), hence the differences might not be so clear. Let's now find the *mean temperatures* from May and June 2017 in Kumpula and Rovaniemi.

- From the `kumpula` and `rovaniemi` DataFrames, select the rows where values of the `YR--MODAHRMN` column are from May 2017
    - Assign these selected rows to the variables `kumpula_may` and `rovaniemi_may` (you can check the [hints](https://geo-python.github.io/site/lessons/L5/exercise-5.html) for help!)
- Repeat the procedure for the month of June and assign those values to variables to `kumpula_june` and `rovaniemi_june`

In [22]:
# Select the subset of the Kumpula and Rovaniemi data for the 5th and 6th month
kumpula_may = kumpula.loc[kumpula['YR--MODAHRMN'] >= 201705010000]
rovaniemi_may = rovaniemi.loc[rovaniemi['YR--MODAHRMN'] >= 201705010000]

##### SKIPPED THE JUNE PART. IT IS THE SAME ######
kumpula_may.head()

   Unnamed: 0   USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0        8770  29980  201705010000  37.0  NaN  NaN  2.777778
1        8771  29980  201705010100  37.0  NaN  NaN  2.777778
2        8772  29980  201705010200  37.0  NaN  NaN  2.777778
3        8773  29980  201705010300  37.0  NaN  NaN  2.777778
4        8774  29980  201705010400  39.0  NaN  NaN  3.888889

Check that the subsets look ok:

In [23]:
print(f"First values in May, Kumpula:\n{kumpula_may.head()}\n")
print(f"Last values in May, Kumpula:\n{kumpula_may.tail()}")

First values in May, Kumpula:
   Unnamed: 0   USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0        8770  29980  201705010000  37.0  NaN  NaN  2.777778
1        8771  29980  201705010100  37.0  NaN  NaN  2.777778
2        8772  29980  201705010200  37.0  NaN  NaN  2.777778
3        8773  29980  201705010300  37.0  NaN  NaN  2.777778
4        8774  29980  201705010400  39.0  NaN  NaN  3.888889

Last values in May, Kumpula:
      Unnamed: 0   USAF  YR--MODAHRMN  TEMP  MAX  MIN    Celsius
2919       11689  29980  201708311900  64.0  NaN  NaN  17.777778
2920       11690  29980  201708312000  64.0  NaN  NaN  17.777778
2921       11691  29980  201708312100  64.0  NaN  NaN  17.777778
2922       11692  29980  201708312200  64.0  NaN  NaN  17.777778
2923       11693  29980  201708312300  64.0  NaN  NaN  17.777778

In [19]:
print(f"First values in June, Kumpula:\n{kumpula_june.head()}\n")
print(f"Last values in June, Kumpula:\n{kumpula_june.tail()}")

NameError: name 'kumpula_june' is not defined

In [20]:
print(f"First values in May, Rovaniemi:\n{rovaniemi_may.head()}\n")
print(f"Last values in May, Rovaniemi:\n{rovaniemi_may.tail()}")

First values in May, Rovaniemi:
Empty DataFrame
Columns: [Unnamed: 0, USAF, YR--MODAHRMN, TEMP, MAX, MIN, Celsius]
Index: []

Last values in May, Rovaniemi:
Empty DataFrame
Columns: [Unnamed: 0, USAF, YR--MODAHRMN, TEMP, MAX, MIN, Celsius]
Index: []

In [ ]:
print(f"First values in June, Rovaniemi:\n{rovaniemi_june.head()}\n")
print(f"Last values in June, Rovaniemi:\n{rovaniemi_june.tail()}")

### Part 4 (1 point)

Now you can make your temperature data from both locations and months easier to compare by printing out a few useful values.

- Use the `print()` function to show the mean, min and max Celsius temperatures for both places in May and June using the new subset dataframes (`kumpula_may`, `rovaniemi_may`, `kumpula_june`, and `rovaniemi_june`).

In [32]:
# YOUR CODE HERE
print(f"Mean temperature in Kumpula in may is {kumpula_may['TEMP'].mean()}")
# NOTE: the use of '' within the "" since otherwise python gets confused where the string ends

Mean temperature in Kumpula in may is 57.07079343365253

### Problem 3 summary

In the spirit of [knowledge discovery](http://researcher.ibm.com/researcher/view_group.php?id=144), let's briefly interpret the results of the data analysis in Problem 3. Please answer the following questions based on the data analysis results from this problem:

- Does there seem to be a large difference in temperatures between the months?
- Is Rovaniemi a much colder place than Kumpula?

Also, be sure to:

- Check that your code includes informative comments explaining what your code does
- Commit and push your changes to your GitHub repository for Exercise 5

YOUR ANSWER HERE

### On to Problem 4 (*optional*)

Now you can continue to the *optional* [Problem 4: Data analysis](Exercise-5-problem-4.ipynb)