## Problem 2 - Data manipulation and selection (4 points)

In this problem you will clean the data from our data file by removing no-data values, convert temperature values in Fahrenheit to Celsius, and split the data into separate datasets using the weather station identification code. We will start this problem by cleaning and converting our temperature data. Please perform the tasks below by writing your code into the code cells in each section.

### Tips for completing this problem

- Use **exactly** the same variable names as in the instructions because your answers will be automatically graded, and the tests that grade your answers rely on following the same formatting or variable naming as in the instructions.
- **Please do not**:

    - **Change the file names**. Do all of your editing in the provided `Exercise-5-problem-2.ipynb` file (this file).
    - **Copy/paste cells in this notebook**. We use an automated grading system that will fail if there are copies of code cells.
    - **Change the existing cell types**. You can add cells, but changing the cell types for existing cells (from code to markdown, for example) will also cause the automated grader to fail. 

### Scores for this problem

**Your score on this problem will be based on following criteria:**

- Creating a new dataframe called `selected` that contains select columns from the data file
- Cleaning the new dataframe by removing no-data values
- Creating a new column for temperatures converted from Fahrenheit to Celsius
- Dividing the data into separate dataframes for the Helsinki Kumpula and Rovaniemi stations
- Saving the new dataframes to CSV files
- Including comments that explain what most lines in the code do
- Answering a couple questions at the end of the problem
- Uploading your notebook and data files to your GitHub repository for this week's exercise

## AI tool usage agreement

**Enter your name (and that of your partner) in the cell below** to confirm that you have followed the [course guidelines on the use of AI tools](https://geo-python-site.readthedocs.io/en/latest/course-info/ai-tools.html) and understand that misuse of AI tools is considered cheating.

YOUR ANSWER HERE

### Part 1 (0 points)

The first step for this problem is to read the data file `6153237444115dat.csv` again into a variable `data` using pandas. Remember to specify the no-data values (you can copy your code from Problem 1).

In [2]:
!pip install pandas # to install the library if it is not available

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (91 kB)
Collecting numpy>=1.22.4 (from pandas)
  Downloading numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from pandas) (2025.2)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (12.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 6.7 MB/s  0:00:01m0:00:0100:01
Downloading numpy-2.2.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 14.6 MB/s  0:00:01 eta 0:00:01
Downloading tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]2m2/3 [pandas]
Successfully installed numpy-2.2.6 pandas-2.3.3 tzdata-2025.3

In [3]:
import pandas as pd

In [5]:
# read data, note to change all the missing values to NAs
data = pd.read_csv("data/6153237444115dat.csv",na_values=['*', '**', '***', '****', '*****', '******'])

Check that the first rows of the DataFrame look ok:

In [6]:
# Check the first 5 rows:
data.head()

,USAF,WBAN,YR--MODAHRMN,DIR,SPD,GUS,CLG,SKC,L,M,...,SLP,ALT,STP,MAX,MIN,PCP01,PCP06,PCP24,PCPXX,SD
0,28450,99999,201705010000,174.0,10.0,14.0,NaN,NaN,NaN,NaN,...,1009.2,NaN,984.1,NaN,NaN,NaN,NaN,NaN,NaN,35.0
1,28450,99999,201705010020,180.0,10.0,NaN,4.0,NaN,NaN,NaN,...,NaN,29.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,28450,99999,201705010050,190.0,10.0,NaN,4.0,NaN,NaN,NaN,...,NaN,29.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,28450,99999,201705010100,188.0,12.0,16.0,NaN,NaN,NaN,NaN,...,1009.1,NaN,984.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0
4,28450,99999,201705010120,200.0,13.0,NaN,2.0,OBS,NaN,NaN,...,NaN,29.74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Check the number of rows in the DataFrame:

In [7]:
# Check the number of rows:
len(data)

# Check number of columns and rows:
data.shape

(11694, 33)

### Part 2 (1 point)

Next, your task is to subset the data and remove rows with missing temperature values.

- Select the columns `USAF`, `YR--MODAHRMN`, `TEMP`, `MAX`, and `MIN` from the `data` dataframe and assign them to the variable `selected`
- Remove all rows from `selected` that have NoData in the column `TEMP` using the `dropna()` function

In [12]:
# Select the specific columns from the data:
selected = data[["USAF","YR--MODAHRMN","TEMP","MAX","MIN"]]

# check that it worked:
selected.head()
len(selected) # 11694
# Remove the rows from the "selected" data with no data in the column TEMP
cols_to_check = ["TEMP"]
selected = selected.dropna(subset = cols_to_check)
#OR
selected = selected.dropna(subset = ["TEMP"])

selected.head()
len(selected) # 11691

11691

Check that you selected the correct column names:

In [9]:
selected.head()

    USAF  YR--MODAHRMN  TEMP  MAX  MIN
0  28450  201705010000  31.0  NaN  NaN
1  28450  201705010020  30.0  NaN  NaN
2  28450  201705010050  30.0  NaN  NaN
3  28450  201705010100  31.0  NaN  NaN
4  28450  201705010120  30.0  NaN  NaN

Check how many rows you have after removing the no-data values:

In [10]:
len(selected)

11691

### Part 3 (1 point)

Next, you can convert the temperature values in Fahrenheit to Celsius.

- Create a new column in `selected` called `Celsius`
- Convert the Fahrenheit temperatures from `TEMP` using the conversion formula below and store the results in the new `Celsius` column.

$$
\Large
\begin{equation}
  T_{\mathrm{Celsius}} = (T_{\mathrm{Fahrenheit}} - 32)~/~1.8
\end{equation}
$$

- Round the values in the `Celsius` column to have 0 decimals (**do not** create a new column, update the current one)
- Convert the `Celsius` values into integers (**do not** create a new column, update the current one)

In [13]:
selected["Celsius"] = (selected["TEMP"] - 32)/1.8
selected.head()

# you will get a warning because you are now working with a slice of a data

    USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0  28450  201705010000  31.0  NaN  NaN -0.555556
1  28450  201705010020  30.0  NaN  NaN -1.111111
2  28450  201705010050  30.0  NaN  NaN -1.111111
3  28450  201705010100  31.0  NaN  NaN -0.555556
4  28450  201705010120  30.0  NaN  NaN -1.111111

In [ ]:
# Check your dataframe
selected.head()

In [ ]:
# Check data types
print(selected.dtypes)

### Part 4 (1 point)

Your next task is to divide `selected` into two separate dataframes. Please use the given variable names and write your answer in the code cell below.

- Select all rows from the `selected` DataFrame with the `USAF` code `29980` and store them in a variable called `kumpula`
- Select all rows from the `selected` DataFrame with the `USAF` code `28450` and store them in a variable called `rovaniemi`

In [26]:
# what to select:
criteria = [29980]

# create selection of just kumpula:
kumpula = selected.loc[selected["USAF"].isin(criteria)]

# OR:
kumpula = selected.loc[selected["USAF"].isin([29980])]
# OR 
kumpula = selected["USAF"] == 29980

# do the same for rovaniemi:
rovaniemi = selected.loc[selected["USAF"].isin([28450])]

# NOTE ISIN CAN NOT DOES NOT UNDERSTAND MATHEMATICAL CALCULATIONS, SO IT HAS TO BE EXACT NUMBER:

In [19]:
# Check the dataframe
print(f"Kumpula: \n{kumpula.head()}\n")

Kumpula:
       USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
8770  29980  201705010000  37.0  NaN  NaN  2.777778
8771  29980  201705010100  37.0  NaN  NaN  2.777778
8772  29980  201705010200  37.0  NaN  NaN  2.777778
8773  29980  201705010300  37.0  NaN  NaN  2.777778
8774  29980  201705010400  39.0  NaN  NaN  3.888889

In [20]:
# Check the dataframe
print(f"Rovaniemi: \n{rovaniemi.head()}\n")

Rovaniemi:
    USAF  YR--MODAHRMN  TEMP  MAX  MIN   Celsius
0  28450  201705010000  31.0  NaN  NaN -0.555556
1  28450  201705010020  30.0  NaN  NaN -1.111111
2  28450  201705010050  30.0  NaN  NaN -1.111111
3  28450  201705010100  31.0  NaN  NaN -0.555556
4  28450  201705010120  30.0  NaN  NaN -1.111111

### Part 5 (1 point)

Now you can save your selections to csv files.

- Save the `kumpula` DataFrame in the file `Kumpula_temps_May_Aug_2017.csv` (CSV format)
- Save the `rovaniemi` DataFrame in the file `Rovaniemi_temps_May_Aug_2017.csv` (CSV format)

For each file, be sure to 

- Separate the columns with commas (`,`)
- Use only 2 decimals for the floating point numbers

Remember to commit both data files to your Exercise 5 repository!

In [25]:
# YOUR CODE HERE
output_fp = "data/Kumpula_temps_May_Aug_2017.csv"

# Save DataFrame to csv
kumpula.to_csv(output_fp, sep=",") # clarify what seperator you want to use

#OR
kumpula.to_csv("data/Kumpula_temps_May_Aug_2017.csv", sep=",") # clarify what seperator you want to use

# same for rovaniemi
rovaniemi.to_csv("data/Rovaniemi_temps_May_Aug_2017.csv", sep=",") # clarify what seperator you want to use

In [ ]:
#Read-only cell for hidden tests :)

### Problem 2 summary

- Was anything unclear to you in Problem 2?
- Did you encounter any problems with decimal formatting?

Also, make sure you:

- Check that your code includes informative comments explaining what your code does
- Commit and push your changes to your GitHub repository for Exercise 5 (including your 2 new data files)

Please write your answers and comments below (**activate the cell by double clicking**).

YOUR ANSWER HERE

### On to Problem 3

Now you can continue to [Problem 3: Data analysis](Exercise-5-problem-3.ipynb)